version: "3"
services:
  postgresdbkiller:
    image: postgres:15.2-alpine
    container_name: postgresdbkiller
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: KillerBee
      POSTGRES_USER: Killer
      POSTGRES_PASSWORD: shwNaNEMKjBjdUX

    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data